# Generated by Django 5.0.3 on 2024-04-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaidTo', models.CharField(max_length=122)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateField()),
                ('Reason', models.CharField(max_length=50)),
                ('Remarks', models.CharField(max_length=122)),
            ],
        ),
    ]
